language: ruby
rvm:
  - 2.3.1

env:
  - RAILS_VERSION='4.2.6'

branches:
  only:
    - master
    - development
    - staging
before_script:
  - gem install bundler -v 0.13
  - bundle install
  - psql -c "CREATE USER webx SUPERUSER PASSWORD 'webx';" -U postgres
  - rake db:create
  - rake db:migrate
  - bundle exec rails --version

addons:
  postgresql: '9.5'
