language: ruby
rvm:
  - 2.3.1

env:
  - RAILS_VERSION='4.2.6'

branches:
  only:
    - master
    - development
    - staging
before_script:
  - sudo /etc/init.d/postgresql stop
  - wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
  - sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ precise-pgdg main 9.5" >> /etc/apt/sources.list.d/postgresql.list'
  - sudo apt-get update
  - sudo apt-get install postgresql-9.5 postgresql-contrib-9.5
  - sudo /etc/init.d/postgresql start
  - psql --version
  - psql -c "CREATE USER webx SUPERUSER PASSWORD 'webx';" -U postgres
  - rake db:create
  - rake db:migrate
  - bundle exec rails --version

addons:
  postgresql: '9.5'
