language: ruby
rvm:
  - 2.3.1

env:
  global:
    - RAILS_VERSION='4.2.6'
    - PGPORT=5433
    - PGHOST=localhost

branches:
  only:
    - master
    - development
    - staging

before_script:
  - sudo cp /etc/postgresql/9.4/main/pg_hba.conf /etc/postgresql/9.5/main/pg_hba.conf
  - sudo /etc/init.d/postgresql restart
  - psql --version
  - psql -c "CREATE USER webx SUPERUSER PASSWORD 'webx';" -U postgres
  - bundle exec rake db:create
  - bundle exec rake db:migrate
  - bundle exec rails --version

addons:
  apt:
    sources:
      - precise-pgdg-9.5
    packages:
      - postgresql-9.5
      - postgresql-contrib-9.5
  postgresql: 9.5
