# Pool nahradte queue ktoru chcete aby bola spustena a cislo urcuje ich pocet
sample_resque_job: 1
crawler_initializer: 1

production:
  sample_resque_job: 1
  crawler_initializer: 1

staging:
  sample_resque_job: 1
  crawler_initializer: 1
