sample_resque_job: 1
crawler_initializer: 1
crawler_executer: 1

production:
  sample_resque_job: 1
  crawler_initializer: 1
  crawler_executer: 1

staging:
  sample_resque_job: 1
  crawler_initializer: 1
  crawler_executer: 1
