# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c1cc65ddd64583a0adb417784977de3378e2e5192dfcf015e82fa96992050aa1b21dcd9d65821c8837deb2550d7031f95d298bfbe649b26f766b8c44a272e28f

test:
  secret_key_base: 559d2ffb5712c3b74dff255e78bf91fd2f989226bedf4eaab183866e89b202ec4302b8b75a66fd2912d6701c591aa85018b57227b276031c66e4b8f779bbce53

staging:
  secret_key_base: aea2cec85d3f4d81ed7e3f61575ddfddb71450a1ec465a611279b47e0ad83293d075cd3e22db8c9ec917ad2b2440894fbe06de729cd4f749f1d8a69f14c9c093

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
